# Set the base image.
FROM node:20-alpine

# DEFINE WORKDIR INSIDE THE CONTAINER
WORKDIR /usr/src/app

# Install the application's dependencies into the node_modules's cache directory.
COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY . /usr/src/app/

EXPOSE 6006

CMD ["npm", "run", "storybook"]