---
name: Build and Publish Storybook to GitHub Pages
on:
    push:
        branches:
            - main
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Install Dependencies and Build Storybook
              run: |
                  cd storybook
                  npm ci
                  npm run build-storybook

            - name: Deploy Storybook to GitHub Pages
              run: |
                  npx bitovi/github-actions-storybook-to-github-pages@v1.0.3 --path storybook-static
              working-directory: storybook
